language: node_js
sudo: false
node_js: "10"
cache: yarn
dist: bionic

addons:
  chrome: "stable"
  firefox: "latest"

notifications:
  email:
    - vieira.joaopaulo.91@gmail.com

before_script: "yarn lint"
