language: node_js
node_js: "12"
cache: npm
os: linux
dist: bionic

addons:
  chrome: "stable"
  firefox: "latest"

notifications:
  email:
    - vieira.joaopaulo.91@gmail.com

before_script: "npm run lint"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"